on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - uses: pre-commit/action@v3.0.1

      - name: Run pre-commit on all files
        run: pre-commit run --all-files
